// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iufusjfdksbqnzekciyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1ZnVzamZka3NicW56ZWtjaXlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MjM0NTMsImV4cCI6MjA3MzQ5OTQ1M30.w0KxAyj5YwJKTbTxgEO9JwPurpAXa7UiWGlcKR1YVPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});